docs/SOURCES.md
docs/TEST-PLAN.md

Created test plan.  Added to source file.

Creation of Test Plan

---

docs/README.md

Added Setup and Startup to README.md file

README setup/startup Section

---

docs/README.md

I only added the readme file, so no other files are coming through in this update.

added cloning repo into the Read-me instructions

---

src/exsm3951_bookswap/bookswap/tests.py

added a note that said I would add more edge cases on the weekend.

Added some fail cases to testing

---

docs/README.md

- Added "Project Usage" section to README

README - Project Usage 

---

src/exsm3951_bookswap/bookswap/urls.py
src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/browse/browse.html
src/exsm3951_bookswap/templates/library/library.html

- Implemented view to delete a wishlist item
- Added "remove" button to each wishlist item card in the library page
- On the browse page, changed to not show "Add to wishlist" button when the book is already in your wishlist

Wishlist - Remove Item

---

src/exsm3951_bookswap/authentication/views.py

- When on the login page, redirect user to library view when already authenticated

Login Page - Hide when authenticated

---

src/exsm3951_bookswap/templates/library/library.html

Added book image  for **My Book Listing** and **Wish List**  on the _Library page_

Image Rendering for Book tiles - Listing Page

---

src/exsm3951_bookswap/bookswap/tests.py
src/exsm3951_bookswap/bookswap/urls.py
src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/base.html
src/exsm3951_bookswap/templates/book-listings/my-book-listings.html
src/exsm3951_bookswap/templates/library/library.html
src/exsm3951_bookswap/templates/wishlist/wishlist.html

- Renamed the "My Library" page to "Library" (this page will only contain the search functionality for other people's listings)
- Moved the "My Listing" section from "Library" to its own page
- Moved the "My Wishlist" section from "Library" to its own page

Library - Separate pages for My Listings and Wishlist

---

src/exsm3951_bookswap/bookswap/views.py

- When a new book listing is created, create notifications for users that have the book that is being listed in their wishlist

Notification - Book Listing Creation

---

src/exsm3951_bookswap/bookswap/views.py

- Added comments in notifications code section

Added Comments 

---

src/exsm3951_bookswap/bookswap/views.py

- after adding and saving a book it redirects back to browse page

Redirect Browse Page After Creating a Book

---

src/exsm3951_bookswap/profile/forms.py
src/exsm3951_bookswap/profile/views.py
src/exsm3951_bookswap/templates/profile/settings.html

fixed profile page so that the profile updated when saved.
Added the shipping section.

Finished Profile Page

---

src/exsm3951_bookswap/templates/help/help.html

Added about section
made questions into dropdowns

Touched up page, added about section

---

docs/DESIGN.md

###Summary
Restored ERD diagram to appear in the Design file. Link was for some reason broken.

ERD diagram link broken

---

src/exsm3951_bookswap/templates/base.html
src/exsm3951_bookswap/templates/partials/nav_links.html

Fixed nav bar so that the nav links don't overlap with the welcome message
added a hamburger menu to the mobile version

Fixed nav bar & added hamburger menu to mobile view

---

src/exsm3951_bookswap/templates/base.html
src/exsm3951_bookswap/templates/library/library.html
src/exsm3951_bookswap/templates/profile/settings.html

change global font colour in base.html,
style library.html
style settings.html

change global font colour in base.html, style library&settings.html

---

src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/library/my_library.html

###Summary 
- Browse to search book 'save' a book was not saving it to the book table and not rendering on frontend
- the fixed **"book_create_from_search"** in views that was the cause

View Function for Create a Book Correction

---

src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/library/library.html

- fixed broken image link for books in the Library.html template
- fixed attribute name for library_view in views to fetch all users owned books 
- and other minor fixes to render views in frontend

Fixing Broken Links and Views Issues

---

src/exsm3951_bookswap/bookswap/views.py

- On the transactions page, reordered transactions to display latest first

Transactions - Display Order

---

src/exsm3951_bookswap/bookswap/forms.py
src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/browse/browse.html
src/exsm3951_bookswap/templates/partials/book_form.html

got Add Book to be read only
got search to return to search when you cancel instead of going back to browse
fixed issue where In Your Library wasn't working

Updated Browse Page

---

src/exsm3951_bookswap/bookswap/urls.py
src/exsm3951_bookswap/bookswap/views.py
src/exsm3951_bookswap/templates/book-listings/book-listing.html
src/exsm3951_bookswap/templates/library/library.html
src/exsm3951_bookswap/templates/partials/nav_links.html

made it so all listings show, then search refines the listing.
Added a close button into the listing

Nancy all listings show

---

docs/DESIGN.md

ERD diagram and Schema minor revision:
- added LibraryItem table to ERD diagram 
- amended schema with LibraryItem

Minor changes - ERD diagram and Schema

---

docs/Timesheet.md
src/exsm3951_bookswap/bookswap/forms.py
src/exsm3951_bookswap/templates/book-listings/book-listing.html
src/exsm3951_bookswap/templates/browse/browse.html
src/exsm3951_bookswap/templates/library/edit_review.html
src/exsm3951_bookswap/templates/library/library.html
src/exsm3951_bookswap/templates/library/my_library.html
src/exsm3951_bookswap/templates/notifications/index.html
src/exsm3951_bookswap/templates/partials/book_form.html
src/exsm3951_bookswap/templates/transactions/swap-form.html
src/exsm3951_bookswap/templates/transactions/transactions.html

modified:   bookswap/forms.py
modified:   templates/book-listings/book-listing.html - button colour, center image. 
modified:   templates/browse/browse.html - button styling, placement, header style
modified:   templates/library/library.html - fixed header style 
modified:   templates/library/my_library.html -review display, fixed error where review text would overflow container.
modified:   templates/notifications/index.html fix bug where button would enlarge, center message in container
modified:   templates/partials/book_form.html - fix background colour of of form fields. 
modified:   templates/transactions/swap-form.html - style buttons, and form. 
modified:   templates/transactions/transactions.html - style colours of different transactions and hover.

Styling changes. 

---

src/exsm3951_bookswap/bookswap/tests.py
src/exsm3951_bookswap/bookswap/views.py

added front end tests and a couple more back end tests.
Not comprehensive but good enough.

Nancy testing

---

src/exsm3951_bookswap/bookswap/views.py

Rating and Review 
- fixed issue with having same book and editing review issue

Library Review and Rating issue 
